config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  # root "registrations#new"
  # root to: 'home#index'
  root to: 'registrations#new'
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  delete "logout" , to: "sessions#destroy"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# email:string
# password_digest:string

# password: string virtual 
# password_confirmation: string virtual 

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Must be a valid email address"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def index
    end

    def about	
    end
    
    def new
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
    flash[:notice] = "Logged in Successfully"
    flash[:alert] = "Invalid email or Password"

    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new 
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Account successfully created"
            # redirect home_path to the static resume page
        else 
            render :new, status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def destroy
        session[:user_id] = nil
        redirect_to root_path , notice: "Logged Out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Ruchi Pakhle - My Resume</title>

<meta name="viewport" content="width=device-width"/>
<meta name="description" content="The Curriculum Vitae of Joe Bloggs."/>
<meta charset="UTF-8"> 




</head>
<body id="top">
<div id="cv" class="instaFade">
	<div class="mainDetails">
		<div id="headshot" class="quickFade">
		    <%= image_tag('headshot.jpg', alt: "Ruchi Pakhle") %>
		</div>
		
		<div id="name">
			<h1 class="quickFade delayTwo">Ruchi Pakhle</h1>
			<h2 class="quickFade delayThree">Job Title</h2>
		</div>
		
		<div id="contactDetails" class="quickFade delayFour">
			<ul>
				<li>email: <a href="mailto:joe@bloggs.com" target="_blank"> ruchipakhle@gmail.com</a></li>
				<li>linkedin: <a href="https://www.linkedin.com/in/ruchi-pakhle-a0a5311b0/"> Ruchi Pakhle</a></li>
				<li>twitter: <a href="https://twitter.com/Ruchicodess"> @Ruchicodess</a></li>
				<li>Phone: 9167527193</li>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
	
	<div id="mainArea" class="quickFade delayFive">
		<section>
			<article>
				<div class="sectionTitle">
					<h1>What I Do</h1>
				</div>
				
				<div class="sectionContent">
					<p>I'm Ruchi Pakhle, currently pursuing my Bachelor's degree in Computer Science Engineering with a 9.88 GPA. I have a good hold over these technical skills, including Data Structures & Algorithms (C++) and Web Development(MERN).  I'm also a regular contributor to open-source projects. I've worked on several open-source projects, including the GirlScript Summer of Code and Script Fellowship Program. I'm currently working as an open-source contributor at Moja Global,  a mentor for Script Winter of Code 2.0 & an OSS contributor at FOSSASIA.</p>
				</div>
			</article>
			<div class="clear"></div>
		</section>
		
		
		<section>
			<div class="sectionTitle">
				<h1>Work Experience</h1>
			</div>
			
			<div class="sectionContent">
				<article>
					<h2>Open-Source Contributor at Moja-Global</h2>
					<p class="subDetails">Jan 2022 - Present</p>
					<p>Working on a case study for the C++ MRV profiling for the FLINT based on various models and also contributing to moja-global docs repository as a part of the Winter of Code 2.0.</p>
				</article>
				
				<article>
					<h2>Web Developer at DIY</h2>
					<p class="subDetails">June 2021 - September 2021</p>
					<p>Worked on the frontend part for the Resume Build website from scratch using ReactJs and included features that increased the credibility of the web app.</p>
				</article>
				
			</div>
			<div class="clear"></div>
		</section>
		
		
		<section>
			<div class="sectionTitle">
				<h1>Key Skills</h1>
			</div>
			
			<div class="sectionContent">
				<ul class="keySkills">
					<li>C++</li>
					<li>HTML</li>
					<li>CSS</li>
					<li>JS</li>
					<li>ReactJS</li>
					<li>Git</li>
				
				</ul>
			</div>
			<div class="clear"></div>
		</section>
		
		
		<section>
			<div class="sectionTitle">
				<h1>Education</h1>
			</div>
			
			<div class="sectionContent">
				<article>
					<h2>Mahatma Gandhi Missions College of Engineering & Technology</h2>
					<p class="subDetails">BE - (2019-2023)</p>
					<p>CGPA - 9.88</p>
				</article>
				
			</div>
			<div class="clear"></div>
		</section>

		<section>
			<div class="sectionTitle">
				<h1>Achievements</h1>
			</div>
			
			<div class="sectionContent">
				<ul class="keySkills">
					<li>Secured a Rank 3793 among 20K+ applicants in Google Code Jam to I/O for Women 2021</li>
					<li>Secured a position in the top 50 teams & qualified for prototype round in Zeta Hacks 3.0</li>
					
					<br><br/>
				
				</ul>
			</div>
			<div class="clear"></div>
		</section>
		
	</div>
</div>
</body>
</html>

app/views/home/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Hello World! Ruchi here...</h1>
</div>
<br/>
<br/>

<% if @user %>
    Logged in as: <%= @user.email %>

    <%= button_to "Logout", logout_path, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      
    <title>MyResume</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render partial: "shared/navbar" %>
    <div class="container">
      <br/>
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-primary" role="alert">
    <%= flash[:notice] %> 
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-warning" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>
  

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "MyResume", root_path, class:"navbar-brand" %>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
        
      </ul>
      <form class="d-flex">
        
        <%= link_to "Logout", root_path, class:"btn btn-outline-success" %>
      </form>
    </div>
  </div>
</nav>